services:
    backend:
        build: backend
        ports:
            - '3000:3000'
    frontend:
        image: nginx:alpine
        ports:
            - '80:80'
        volumes:
            - ./frontend/dist:/usr/share/nginx/html:ro